server.port=8080
eureka.client.serviceUrl.defaultZone=http://eureka-server:8080/eureka

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds= 1000000
hystrix.command.default.execution.isolation.strategy= THREAD

ribbon.ReadTimeout=60000
